### ISSUE TITLE
Updating this project?

### ISSUE THREAD

**Issue by Colink02** [sym3tri/CSS-Inject#4]
Hey, I was wondering if you were going to continue with this because what I'd like is to change the divs and other tags to black instead of white and edit the sidebar since i cant really change that without going into dev tools(Which our admin blocks annoyingly) constantly. This is really the only way i can customize the browser because they allowed this extension.

Thanks,
Colink02

**Comment by Colink02** [comment]
Never mind happened to find out that it was just chrome preventing it due to CORB(Content-Orgin Read Blocking) due to using raw github.
If your looking on how to fix this i used https://rawgit.com/ to make it a text/stylesheet instead of text/plain

Love the extension :D

Colin

**Comment by sym3tri** [comment]
thanks for the note. glad you like it. 

i'm not really maintaining this much anymore, but if there's a good small general fix i'm happy to accept a pull-request.
